
mex imageset_to_leveldb.cpp -lcaffe -lglog -lgflags -lprotobuf -lleveldb -llmdb ...
    -L/scail/scratch/group/cvgl/hsong/caffe/build/lib ...
 -L/scail/scratch/group/cvgl/hsong/caffe/build/src/caffe/proto

mex serialized_pairs_to_leveldb.cpp -lcaffe -lglog -lgflags -lprotobuf ...
 -lleveldb -llmdb -L/scail/scratch/group/cvgl/hsong/caffe/build/lib ...
 -L/scail/scratch/group/cvgl/hsong/caffe/build/src/caffe/proto